# Pentagonal numbers are generated by the formula P_n = n(3n-1)/2
# Find the pair of pentagonal numbers P_j and P_k, for which their sum and difference are pentagonal and D=|P_j-P_k| is minimised. What is the value of D?
import math

def generate_pentagonal_number(n):
    return n*(3*n-1)/2

def is_pentagonal(x):
    # x = n(3n-1)/2 = (3n^2 - n)/2
    # 2x = 3n^2 - n
    # 3n^2 - n - 2x = 0
    # by quadratic formula, n = (1 + sqrt(1+24x))/6
    # if n is an integer then x is pentagonal
    return (1 + (1 + 24*x)**0.5) % 6 == 0

def solution():
    k=1
    while True:
        for j in range(1,k):
            a = generate_pentagonal_number(k)
            b = generate_pentagonal_number(j)
            if is_pentagonal(a+b) and is_pentagonal(abs(a-b)):
                print("P_j:", b)
                print("P_k", a)
                print("j:", j)
                print("k:", k)
                return(abs(a-b))
        k += 1

print("Solution:", solution())


