"""Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    T_n= n(n+1)/2   1,3,6,10...
Pentagonal  P_n= n(3n-1)/2   1,5,12,22..
Hexagonal   H_n= n(2n-1)     1,6,15,28...

It can be verified that

T_285=P_165=H_143=40755

Find the next triangle number that is also pentagonal and hexagonal"""
import math

#n.b. every hexagonal number is triangular
def hexagonal(n):
    return n*(2*n-1)

def pentagonal(n):
    return n*(3*n-1)/2

def solution():
    # P_165=H_143=40755
    hexagon=40755
    pentagon=40755
    pentagon_index=165
    hexagon_index=143

    while True:
        while hexagon > pentagon:
            pentagon=pentagonal(pentagon_index) # generate next pentagonal number
            if hexagon == pentagon:
                return hexagon
            pentagon_index+=1
        hexagon=hexagonal(hexagon_index)
        hexagon_index+=1

def is_triangle(num):
    # reversing the formula
    a=num*2 # n(n+1)
    b=math.floor(math.sqrt(a))
    c=(a-b)
    n=math.sqrt(c) # approximate n
    return n*(n+1)/2 == num # applying the formula to our estimate of 'n' returns 'num' if 'num' is triangular

def is_pentagonal(num):
    a=num*2
    b=a/3
    n=math.ceil(math.sqrt(b))
    return n*(3*n-1)/2==num

def is_hexagonal(num):
    a=num/2
    n=math.ceil(math.sqrt(a))
    return n*(2*n-1) == num



def main():
    print(solution())

if __name__ == "__main__":
    main()
